/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef ARK_WEB_BRIDGE_TYPES_H_
#define ARK_WEB_BRIDGE_TYPES_H_
#pragma once

///
/// Note: Only add an enum value before ARK_WEB_BRIDGE_BUTT.
///
enum ArkWebBridgeType {
  ARK_WEB_ACCESSIBILITY_EVENT_CALLBACK = 0,
  ARK_WEB_ACCESSIBILITY_NODE_INFO,
  ARK_WEB_ACCESS_REQUEST,
  ARK_WEB_BOOL_VALUE_CALLBACK,
  ARK_WEB_CONSOLE_LOG,
  ARK_WEB_CONTEXT_MENU_CALLBACK,
  ARK_WEB_CONTEXT_MENU_PARAMS,
  ARK_WEB_CONTROLLER_HANDLER,
  ARK_WEB_COOKIE_MANAGER,
  ARK_WEB_DATA_BASE,
  ARK_WEB_DATA_RESUBMISSION_CALLBACK,
  ARK_WEB_DATE_TIME_CHOOSER_CALLBACK,
  ARK_WEB_DATE_TIME_SUGGESTION,
  ARK_WEB_DOH_CONFIG,
  ARK_WEB_DOWNLOAD_CALLBACK,
  ARK_WEB_DOWNLOAD_MANAGER,
  ARK_WEB_DRAG_DATA,
  ARK_WEB_ENGINE,
  ARK_WEB_ENGINE_INIT_ARGS,
  ARK_WEB_FILE_SELECTOR_PARAMS,
  ARK_WEB_FIND_CALLBACK,
  ARK_WEB_FULL_SCREEN_EXIT_HANDLER,
  ARK_WEB_GEO_LOCATION_CALLBACK,
  ARK_WEB_HANDLER,
  ARK_WEB_HISTORY_ITEM,
  ARK_WEB_HISTORY_LIST,
  ARK_WEB_HIT_TEST_RESULT,
  ARK_WEB_JS_DIALOG_RESULT,
  ARK_WEB_JS_HTTP_AUTH_RESULT,
  ARK_WEB_JS_PROXY_CALLBACK,
  ARK_WEB_JS_RESULT_CALLBACK,
  ARK_WEB_JS_SSL_ERROR_RESULT,
  ARK_WEB_JS_SSL_SELECT_CERT_RESULT,
  ARK_WEB_KEY_EVENT,
  ARK_WEB_LOAD_COMMITTED_DETAILS,
  ARK_WEB_LONG_VALUE_CALLBACK,
  ARK_WEB_MESSAGE,
  ARK_WEB_MESSAGE_VALUE_CALLBACK,
  ARK_WEB_NATIVE_EMBED_DATA_INFO,
  ARK_WEB_NATIVE_EMBED_INFO,
  ARK_WEB_NATIVE_EMBED_TOUCH_EVENT,
  ARK_WEB_NWEB,
  ARK_WEB_NWEB_CREATE_INFO,
  ARK_WEB_OUTPUT_FRAME_CALLBACK,
  ARK_WEB_PREFERENCE,
  ARK_WEB_QUICK_MENU_CALLBACK,
  ARK_WEB_QUICK_MENU_PARAMS,
  ARK_WEB_RELEASE_SURFACE_CALLBACK,
  ARK_WEB_RESOURCE_READY_CALLBACK,
  ARK_WEB_SCREEN_CAPTURE_ACCESS_REQUEST,
  ARK_WEB_SCREEN_LOCK_CALLBACK,
  ARK_WEB_SELECT_POPUP_MENU_CALLBACK,
  ARK_WEB_SELECT_POPUP_MENU_ITEM,
  ARK_WEB_SELECT_POPUP_MENU_PARAM,
  ARK_WEB_STRING_VALUE_CALLBACK,
  ARK_WEB_STRING_VECTOR_VALUE_CALLBACK,
  ARK_WEB_TOUCH_HANDLE_STATE,
  ARK_WEB_TOUCH_POINT_INFO,
  ARK_WEB_URL_RESOURCE_ERROR,
  ARK_WEB_URL_RESOURCE_REQUEST,
  ARK_WEB_URL_RESOURCE_RESPONSE,
  ARK_WEB_VALUE,
  ARK_WEB_WEB_STORAGE,
  ARK_WEB_WEB_STORAGE_ORIGIN,
  ARK_WEB_WEB_STORAGE_ORIGIN_VECTOR_VALUE_CALLBACK,

  /*Note: Only add an enum value before ARK_WEB_BRIDGE_BUTT*/
  ARK_WEB_BRIDGE_BUTT
};

#endif // ARK_WEB_BRIDGE_TYPES_H_